name: Deploy Remoto  170 -- sa-wfm-event-consumer-svc -- 
on:
  workflow_dispatch:
    branches:
      - main # O la rama que desees
jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Copiar código
        uses: actions/checkout@v3

      - name: Añadir clave SSH al agente
        uses: webfactory/ssh-agent@v0.4.1
        with:
         ssh-private-key: ${{secrets.SSH_PRIVATE_KEY_170}} # Clave privada

      - name: Conectar y ejecutar comandos en el servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST_170}} # Tu nombre de host
          username: ${{secrets.SSH_USERNAME_170}} # nombre de usuario
          key: ${{secrets.SSH_PRIVATE_KEY_170}} # Clave privada
          script: |
            echo "### path servidor 170 ###"
            cd /home/GIT
            pwd
            ls -lrt 
            echo "###  respaldo del repositorio del servidor ###"
            mv sa-external-event-ingestor-svc /home/GIT/sa-external-event-ingestor-svc_$(date +'%Y%m%d-%H%M')
            ls -lrt 
            echo '### Clonar el repositorio sa-external-event-ingestor-svc ###'
            git clone -b main https://${{secrets.GH_ACCESS_KEY}}@github.com/jeacor/sa-external-event-ingestor-svc.git
            echo '### Repositorio clonado ###' 
            ls -lrt
            sleep 20
            echo '### Detener y eliminar el Contenedor sa-external-event-ingestor-svc ###'
            docker ps
            docker stop wfm-producer-app
            sleep 20
            docker rm wfm-producer-app
            echo '### eliminimar la imagen ###'
            docker images
            sleep 20
            docker rmi wfm-producer
            docker images
            echo '### Ejecutar el build y el deploy ###'
            cd /home/GIT/sa-external-event-ingestor-svc
            ls -lrt
            docker build -t wfm-producer .
            sleep 40
            docker run -d -p 5000:8080 -v dataprotection-keys:/root/.aspnet/DataProtection-Keys --name wfm-producer-app wfm-producer
            sleep 20
            echo '### contenedores corriendo ###'
            docker ps -a
            echo '###### Enviar correo ######'
            cd /home/GIT
            docker ps -a > deploy.txt
            mail -s "Deploy realizado proyecto wfm-event-consumer" joseantonio.lopez@seccionamarilla.com < deploy.txt
            echo '###### Fin del workflow ######'
